# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2014 RDK Management, LLC. All rights reserved.
# ============================================================================
RM          := rm -rf 
CFLAGS      := -g -fPIC -D_REENTRANT -Wall
LIBNAME     := IARMBus
LIBNAMEFULL := lib$(LIBNAME).so
ifeq ($(USE_DBUS),y)
OBJS        := libIARM-dbus.o  libIBus-dbus.o  libIBusDaemon-dbus.o 
EXECUTABLE  := $(patsubst %-dbus.c,%,$(wildcard *Main-dbus.c))
else
OBJS        := libIARM.o  libIBus.o  libIBusDaemon.o 
EXECUTABLE  := $(patsubst %.c,%,$(wildcard *Main.c))
endif
INCLUDE = -I.\
	-I./include	\
	-I$(DFB_ROOT)/usr/local/include/directfb \
	-I$(GLIB_INCLUDE_PATH) \
	-I$(GLIB_CONFIG_INCLUDE_PATH)/include/	

ifeq ($(RDK_LOGGER_ENABLED),y)

INCLUDE += -I$(COMBINED_ROOT)/rdklogger/include 
LDFLAGS+= -L$(COMBINED_ROOT)/rdklogger/build/lib -lrdkloggers
CFLAGS      += -DRDK_LOGGER_ENABLED 
endif

CFLAGS      += $(INCLUDE)

ifeq ($(USE_DBUS),y)
LDFLAGS += -L. -lpthread -ldbus-1
CFLAGS += -D_USE_DBUS

ifeq ($(RDK_PLATFORM_SOC),intel)
CFLAGS += -I$(TOOLCHAIN_DIR)/usr/include/dbus-1.0 -I$(TOOLCHAIN_DIR)/lib/dbus-1.0/include
else
CFLAGS += -I$(OPENSOURCE_BASE)/include/dbus-1.0 -I$(OPENSOURCE_BASE)/lib/dbus-1.0/include
endif

else #USE_DBUS
CFLAGS      += -I$(FUSION_PATH)/src -I$(FUSION_PATH)/include
FUSION_LIBS=-ldirect -lfusiondale -lfusion  -lpthread
endif

LDFLAGS+=-L$(DFB_LIB) -L$(OPENSOURCE_BASE)/lib
LDFLAGS += $(FUSION_LIBS)  
LDFLAGS+=-L$(GLIB_LIBRARY_PATH)/
LDFLAGS+= -L$(RDK_DIR)/sdk/fsroot/ramdisk/usr/local/lib/ -llog4c
LDFLAGS+=$(GLIBS)

all: clean library executable
	@echo "Build Finished...."

library: $(OBJS)
	@echo "Building $(LIBNAMEFULL) ...."
	$(CXX) $(OBJS) $(CFLAGS) $(LDFLAGS) -shared -o $(LIBNAMEFULL)

ifeq ($(USE_DBUS),y)
executable: IARMDaemonMain-dbus.o library
	$(CXX) $(OBJS) $(CFLAGS) $(LDFLAGS) IARMDaemonMain-dbus.o -o $(EXECUTABLE)
else
executable: IARMDaemonMain.o library
	$(CXX) $(OBJS) $(CFLAGS) $(LDFLAGS) IARMDaemonMain.o -o $(EXECUTABLE)
endif
%.o: %.c
	@echo "Building $@ ...."
	$(CXX) -c $<  $(CFLAGS) -o $@

clean:
	@echo "Cleaning the directory..."
	@$(RM) $(OBJS) $(LIBNAMEFULL)
